---
title: "NPRG survey evaluation"
author: "st."
date: "`r Sys.time()`"
output:
  #bookdown::pdf_document2:
   # extra_dependencies: ["float"]
  bookdown::html_document2:
    global_numbering: TRUE
    number_sections: TRUE
   # code_download: yes
    toc: yes
    toc_depth: 4
    toc_float:
       collapsed: no
       smooth_scroll: no
    self_contained: FALSE #TRUE for standalone html page knit
    css: https://school.dh-index.org/public/papers/011/style_HA.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rlang)
library(xml2)

```

```{r echo=T,warning=FALSE}
#print(head)
utest<-"[ani lo sonderzeichentest אני לאaäoöuüÄÖÜß]"
utest<-chr_unserialise_unicode(utest)
print(utest)
```

# HEAD
CHK: `r utest`       

# NEUROPRAGMATIK rating studie
raw data presentation, live evaluated from dataset on server. graphics to come if theres data at all.  

```{r,echo=F,warning=F,eval=TRUE}
#source("survey_src.R")
scred<-read.csv("../../../local/R/cred_gener.csv")
src<-scred$api[scred$url=="nprg-pure"]
#eval(parse(src, encoding="UTF-8"))
source("import_nprg.r")
#d<-read.csv(src,sep="\t")
d<-ds
#getwd()
#qscheme<-read_xml("nprg-rating-q_layout_RND.xml")
qscheme<-read_xml("nprg-rating-q_layout.xml")

# img<-xml_find_all(qscheme,"page/image")
# img_href<-xml_attr(img,"src")
# img_png<-basename(img_href)
# regx1<-"(NPRG-)(.+)\\.png"
# repl1<-"\\2"
# img_ns<-gsub(regx1,repl1,img_png)
page<-xml_find_all(qscheme,"page")
pid1<-xml_attr(page,"ident")
pid1<-gsub("fern"," ####",pid1)
pstart<-grep("RN1",pid1)+1

m1<-grep("(QU[0-9]{1,2})",colnames(d)) #questioncolumns
pend<-pstart+length(m1)-1
pid<-pid1[pstart:pend]
#pid[1]
#d$MT01
d<-ds
#d<-subset(d,d$MODE=="pretest")
d1<-subset(d,d$MODE=="interview")
d2<-subset(d1,d1$QUESTNNR=="nprg"|d1$QUESTNNR=="qnr2"|d1$QUESTNNR=="qnr4")
d3<-subset(d2,d2$MT01=="ja")
#dna<-!is.na(d1$SERIAL)
#sum(d3$FINISHED)
#sum(dna)
#d2<-subset(d1,dna)
#qarray<-unique(d$QU01)
#qarray<-levels(qarray)
qreplace<-c("no concrete","index","request","undefined","n.a.")
#m<-match(qarray)
m1<-grep("(QU[0-9]{1,2})",colnames(d3)) #questioncolumns
k<-97
#messy data, missing QU19
#d$QU19[1]<-"<NA>"
#d$QU18
#putout(m1[1])
qstart<-m1[1]-1
#colnames(d3)[m1[1:20]]
putout<-function(k){
qx<-d3[,k]
#levels(qx)<-qreplace
#plot()
plot(qx,main=pid[k-qstart])
}
#putout(97)
ld<-length(d3$MODE)

```
## evaluation
dataset: `r ld` observations.

```{r,echo=F,warning=F,eval=TRUE}

for (k in m1){
putout(k)
}

```




