---
#--- official ---#
# Hausarbeit im Seminar: Dynamiken postdeutscher Gegenwartsliteratur, Clara Liso, SS2022 FUB
# im Fach: Allgemeine und Vergleichende Literaturwissenschaften
# eingereicht von Stephan Schwarz
# Abgabe: due

title: "DYN HA / SS22 FUB / Clara Liso"
author: "St. Schwarz"
date: "`r Sys.Date()`"
zotero: AVL_dyn
output: 
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
    self_contained: FALSE #TRUE for standalone html page knit
    #css: ../style_HA.css
#swap / decomment ff .bib/.css references for self compile .Rmd to html
#bibliography: https://raw.githubusercontent.com/esteeschwarz/DH_essais/main/sections/DD/klemm_HA/top/klemm.bib
    css: https://ada-sub.rotefadenbuecher.de/skool/public/papers/011/style_HA.css
bibliography: DYN_HA.bib
---
# A. head
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
to self compile the RMarkdown template to this page in RStudio cf. [@esteeschwarz_klemm_2022-1](https://github.com/esteeschwarz/DH_essais/blob/main/sections/DD/klemm_HA/top/M/klemm_HA_temp_BASE.Rmd)

switch on podcast audio if you like...
```{=html}
<!-- placeholder for begleitaudiospur static .mp3-->
<!----><audio controls>
  <source src="xxxdue.mp3" type="audio/mpeg">
You would hear audio but your browser does not support the audio element.
</audio><!---->
<!-- placeholder for begleitaudiospur spotify podcast-->
<!--<iframe src="xxxdue"></iframe>-->
```

---

# 1. einleitung

# 2. u. wolf

# 3. dokumentation aufbereitung

# 4. some visualisations
## 4.1 basic statistics

```{r eval=TRUE, echo=FALSE, warning=FALSE,message=FALSE}
library(jsonlite)
library(syuzhet)

root<-"~/boxHKW/21S/DH/"
local<-paste0(root,"local/DYN/")
setwd(local)
#src<-"wolf_FF_1.json"
src<-paste0(local,"wolf_FF-LEN_1.json")
#getwd()
#k<-2
#dtatxt<-as.data.frame(fromJSON(src))
dtatxt<-(fromJSON(src))
#cat("load TEI from:",src)
source("~/boxHKW/21S/DH/gith/DH_essais/sections/DYN/DYN_HA/DYN_HA_semantics.R")
```

```{r echo = FALSE,warning=FALSE}
```

```{r echo = FALSE,warning=FALSE}
```

## 4.3 sentiment

```{r eval=TRUE, echo=FALSE, collapse=TRUE, warning=FALSE,message=FALSE}
#calls miracle function from external script:
book<-2
chapter<-1
plot_abs<-0
text<-2
dtatarget<-plotsentiment(dtatxt,book,chapter,plot_abs) #ARG: (set,book,chapter,absolute)
mfw()
```

Q: cf. [[@jockers_2015]](https://www.matthewjockers.net/2015/02/02/syuzhet/)

## 4.5 varianzen
---

# B. REF:
